### ISSUE TITLE
Authentication required message

### ISSUE THREAD

**Issue by Gordonby** [a11ywatch/github-actions#13]
I am attempting to use this action on a site that has no authentication, but am receiving this error;

> Run a11ywatch scan --url https://azure.github.io/AKS-Construction/ --external --save
{"data":null,"message":"Authentication required. Add your authentication header and try again.","success":false}

## To reproduce

```yaml
name: Accessibility
on:
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3

      - uses: a11ywatch/github-action@v1.4.0
        name: Accessibility checks
        with:
          WEBSITE_URL: https://azure.github.io/AKS-Construction/
          FAIL_ERROR_COUNT: 10
          EXTERNAL: false
```
