### ISSUE TITLE
URL_LIST feature suggestion

### ISSUE THREAD

**Issue by Ulthran** [a11ywatch/github-actions#56]
Hi again, sorry for the back to back issues. This one's more of a feature request. I'm trying to run this action on a dev site as part of a CI/CD pipeline. The dev site is an AWS API Gateway (running flask) and has a URL like `https://abcde12345.execute-api.us-east-1.amazonaws.com/dev/`. Whenever I try to run it with `SITE_WIDE` enabled, it runs until I cancel it (I've let it go for an hour plus vs when it's not enabled and it runs in ~5 mins with installation). And it always seems to hang on the `a11ywatch crawl` step.

So my question/feature request is this: would it be possible to add a `URL_LIST` kind of parameter that lets you run `a11ywatch scan` on each specified page instead of using `a11ywatch crawl`? Or, even better, am I just using the action wrong and there's a good way to handle this already? I tried adding a `sitemap.xml` using `flask-sitemapper` (which works) but the action still runs for way longer than it should to scan just the few pages of my site (again, never seen it finish). Is there a better way to strictly limit the crawl to pages off the root URL?

```
web-accessibility-eval:
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Web Accessibility Eval
        uses: a11ywatch/github-action@v2.1.9
        with:
          WEBSITE_URL: "https://abcde12345.execute-api.us-east-1.amazonaws.com/dev/"
          SITE_WIDE: false
          SUBDOMAINS: false
          TLD: false
          SITEMAP: true
          FAIL_ERRORS_COUNT: 15
          LIST: true
          FIX: true
          UPGRADE: false
          UPLOAD: true
        env:
          DEFAULT_RUNNERS: htmlcs,axe
          PAGEMIND_IGNORE_WARNINGS: true
          AI_DISABLED: false
```

Thanks in advance for any help :)
